// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWFhqrFlaFzgimPffkzP4iML3PwGFFpLY',
    appId: '1:639197274226:web:bc41910c00669093efe2eb',
    messagingSenderId: '639197274226',
    projectId: 'savr-sense',
    authDomain: 'savr-sense.firebaseapp.com',
    storageBucket: 'savr-sense.firebasestorage.app',
    measurementId: 'G-4MFRGVDGRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEghBmJquIHuTa0hKXjOKSa_6aFvZQZpg',
    appId: '1:639197274226:android:c95fa7d6b6253650efe2eb',
    messagingSenderId: '639197274226',
    projectId: 'savr-sense',
    storageBucket: 'savr-sense.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmR7wRzikjb5JtvcUJO0adnwyN2GppT6I',
    appId: '1:639197274226:ios:1094562c49a6fbacefe2eb',
    messagingSenderId: '639197274226',
    projectId: 'savr-sense',
    storageBucket: 'savr-sense.firebasestorage.app',
    iosBundleId: 'com.example.savrSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmR7wRzikjb5JtvcUJO0adnwyN2GppT6I',
    appId: '1:639197274226:ios:1094562c49a6fbacefe2eb',
    messagingSenderId: '639197274226',
    projectId: 'savr-sense',
    storageBucket: 'savr-sense.firebasestorage.app',
    iosBundleId: 'com.example.savrSense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWFhqrFlaFzgimPffkzP4iML3PwGFFpLY',
    appId: '1:639197274226:web:22a8281e762b2966efe2eb',
    messagingSenderId: '639197274226',
    projectId: 'savr-sense',
    authDomain: 'savr-sense.firebaseapp.com',
    storageBucket: 'savr-sense.firebasestorage.app',
    measurementId: 'G-CT8878ZK7N',
  );
}
